language: android
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - lynx
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew clean build

after_failure:
  - |
      if [ -f "$TRAVIS_BUILD_DIR/percent-clip-view/build/reports/lint-results.html" ]; then
        lynx -dump "$TRAVIS_BUILD_DIR/percent-clip-view/build/reports/lint-results.html"
        cat "$TRAVIS_BUILD_DIR/percent-clip-view/build/reports/lint-results.html"
      fi
